### ISSUE TITLE
S10: Old Friends fails to load 

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#1]
The map generator messes up and results in an error like this: 
<img width="1792" alt="Screen Shot 2020-11-18 at 00 49 59" src="https://user-images.githubusercontent.com/1388660/99754702-fc492a80-2ab6-11eb-897b-bee324e9ab96.png">

**Comment by cooljeanius** [comment]
Update: I tried making the changes described in wesnoth/wesnoth#5293 and in https://forums.wesnoth.org/viewtopic.php?f=21&t=47614&start=15 but that just resulted in a different error: 
<img width="1792" alt="Screen Shot 2020-11-21 at 20 47 30" src="https://user-images.githubusercontent.com/1388660/99891756-5a9f1600-2c3b-11eb-8785-e46468e9c08b.png">

**Comment by cooljeanius** [comment]
After trying to bring the code a bit closer to the generator code in SoF's "Gathering Materials" I now get this:
<img width="1792" alt="Screen Shot 2020-11-21 at 20 57 07" src="https://user-images.githubusercontent.com/1388660/99891834-4b6c9800-2c3c-11eb-9d92-268fc5d8405a.png">

**Comment by cooljeanius** [comment]
...and now it crashes the entire game: https://cdn.discordapp.com/attachments/442775044590927873/779890890587897926/The_Battle_for_Wesnoth_2020-11-21-210438_Eric-Gallagers-MacBook-Pro-2.crash

**Comment by knyghtmare** [comment]
`[items][/items]` is no longer support in 1.14 so I guess that's causing some issue. 
It's kind of frustrating to read the code in the file since the original scenario designer decided on using macros for `[passage][/passage]` and `[chamber][/chamber]` so most of the times I am lost at trying to discern what the particular parameters map to.
Might tinker with this to try MapGeneratorWML.

**Comment by cooljeanius** [comment]
> `[items][/items]` is no longer support in 1.14 so I guess that's causing some issue.
> It's kind of frustrating to read the code in the file since the original scenario designer decided on using macros for `[passage][/passage]` and `[chamber][/chamber]` so most of the times I am lost at trying to discern what the particular parameters map to.

The `{PASSAGE}` and `{CHAMBER}` macros are defined in `utils/random_map.cfg`

**Comment by knyghtmare** [comment]
I got passed the Assertion Failed error and the scenario loaded but I get the instant "You have been defeated" pop-up and the scenario ends there.

**Comment by knyghtmare** [comment]
Update: Fixed it and scenario loaded...Umm...How do I make a PR without a fork?

**Comment by cooljeanius** [comment]
just send a diff?

**Comment by cooljeanius** [comment]
Fixed.
