### ISSUE TITLE
Allow use of more of the UMC music books

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#11]
Currently, only ~~one~~ three of the UMC music books is usable with this campaign. There are 12 as of the filing of this bug. It would be cool if this campaign could use all of them. Fixing this will require listening to all of the music, and categorizing it to fit under the existing music moods in [`utils/music.cfg`](https://github.com/cooljeanius/The_Earths_Gut/blob/master/utils/music.cfg).

**Comment by cooljeanius** [comment]
if clemmece/qlvorbis#4 were fixed, I'd have an easier time reviewing the music...

**Comment by cooljeanius** [comment]
postponed until a post-BfW-1.16 release...

**Comment by cooljeanius** [comment]
> if [clemmece/qlvorbis#4](https://github.com/clemmece/qlvorbis/issues/4) were fixed, I'd have an easier time reviewing the music...

here's another similar project that might be worth trying to get working: https://github.com/tek-nishi/QLOgg

**Comment by cooljeanius** [comment]
So apparently @kabachuha has a new music pack called "Project Thursagan Music" that might fit perfectly here?

**Comment by kabachuha** [comment]
@cooljeanius it is composed of the most suiting IftU/AtS music + some track from the music books:

```
#
#   * "Ambuscade" by Mattias Westlund (West)
#      http://r.wesnoth.org/t24553
#
#   * "Lonely Snowfall" by Jeremy Nicoll (jeremy2)
#      http://r.wesnoth.org/t18311
#
#   * "gameplay06" by Aleksi Aubry-Carlson (Aleksi)
#
#   * "Climactic Contemplation" by Telaron
#     from "UMC Music Book 8" for Wesnoth 1.10
#
#   * "Western_Theme2" by Telaron
#     from "UMC Music Book 9" for Wesnoth 1.10
#
#   * "Gathering Storm" by Blake Ewing (Ewing)
#      http://r.wesnoth.org/t31003
#
#   * "The High King's March" by Mattias Westlund (West)
#      http://r.wesnoth.org/t27572
#
#   * "Harp" by Telaron
#     from "Aeranor Book I Audio" for Wesnoth 1.10
#
#   * "Moleman" by Telaron
#     http://r.wesnoth.org/t30748 [http://r.wesnoth.org/p513091]
#
#   * "Epic Race" by Telaron
#
#   * "Enchanted Forest" by Tyler Johnson
#     https://r.wesnoth.org/t32419
#
#   * "In the Land of Madness" by Tyler Johnson
#     https://r.wesnoth.org/t32870
#
#   * "In the Land of Madness" by Tyler Johnson
#     https://r.wesnoth.org/t32870
#
#   * "Primitive War Song" by hiro hito
#     from "UMC Music Book 1" for Wesnoth 1.10
#
#   * "High in the Mountains" by Novatlan
#     from "UMC Music Book 1" for Wesnoth 1.10
#
#   * "Flight of the Drakes" by [PA]NotUncleDave
```

**Comment by cooljeanius** [comment]
> @cooljeanius it is composed of the most suiting IftU/AtS music + some track from the music books:
> 
> * "Ambuscade" by Mattias Westlund (West)
>    http://r.wesnoth.org/t24553
> * "Lonely Snowfall" by Jeremy Nicoll (jeremy2)
>    http://r.wesnoth.org/t18311
> * "gameplay06" by Aleksi Aubry-Carlson (Aleksi)
> * "Climactic Contemplation" by Telaron
>   from "UMC Music Book 8" for Wesnoth 1.10
> * "Western_Theme2" by Telaron
>   from "UMC Music Book 9" for Wesnoth 1.10
> * "Gathering Storm" by Blake Ewing (Ewing)
>    http://r.wesnoth.org/t31003
> * "The High King's March" by Mattias Westlund (West)
>    http://r.wesnoth.org/t27572
> * "Harp" by Telaron
>   from "Aeranor Book I Audio" for Wesnoth 1.10
> * "Moleman" by Telaron
>   http://r.wesnoth.org/t30748 [[http://r.wesnoth.org/p513091](http://r.wesnoth.org/p513091)]
> * "Epic Race" by Telaron
> * "Enchanted Forest" by Tyler Johnson
>   https://r.wesnoth.org/t32419
> * "In the Land of Madness" by Tyler Johnson
>   https://r.wesnoth.org/t32870
> * "Primitive War Song" by hiro hito
>   from "UMC Music Book 1" for Wesnoth 1.10
> * "High in the Mountains" by Novatlan
>   from "UMC Music Book 1" for Wesnoth 1.10
> * "Flight of the Drakes" by [PA]NotUncleDave

Hm, if some of them are also in the UMC music books, I might have to watch out for duplication... which ones *aren't* in the music books?

**Comment by kabachuha** [comment]
Well, they all are in music books, except maybe for West's 'The High King's March'

**Comment by cooljeanius** [comment]
> Well, they all are in music books, except maybe for West's 'The High King's March'

OK, I'm going to keep the list in my quote in my previous comment updated as I find more information...

**Comment by cooljeanius** [comment]
Additional info on the UMC music books can be found in @Pentarctagon's thread for them on the forums: https://forums.wesnoth.org/viewtopic.php?p=679190#p679190

**Comment by cooljeanius** [comment]
been working on this a bit more in recent commits; un-postponing

**Comment by cooljeanius** [comment]
So, now that I've got a new mood ("Creepy"), I guess I'd better actually use it... which scenarios do people think it would make most sense for? I'm thinking 05b and 18 for now, but maybe others, too?

**Comment by cooljeanius** [comment]
compare against moods proposed in https://github.com/wesnoth/wesnoth/issues/5767

**Comment by cooljeanius** [comment]
opened a thread on the forums for this: https://forums.wesnoth.org/viewtopic.php?t=57225

**Comment by cooljeanius** [comment]
Technically there are still 2 books left, but I don't really feel like adding them...
