### ISSUE TITLE
Mention Stalrag somewhere

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#13]
This was a request from @knyghtmare on Discord; apparently Stalrag and Hamel are supposed to be old friends...

**Comment by knyghtmare** [comment]
Actually, they are in the classic NR but I have carried it over to the rework as well. Since I think it would be a good thing to do.

**Comment by cooljeanius** [comment]
> Actually, they are in the classic NR but I have carried it over to the rework as well. Since I think it would be a good thing to do.

Suggestions on where to put this mention of Stalrag?

**Comment by knyghtmare** [comment]
Well, for starters....make an effort to make their friendship look old and strong...or just add Stalrag has a loyal and keep in player party.

**Comment by cooljeanius** [comment]
> Well, for starters....make an effort to make their friendship look old and strong...or just add Stalrag has a loyal and keep in player party.

That seems like quite a bit more dialogue than I was originally thinking of; I was thinking it'd be like just a single line or something...

**Comment by knyghtmare** [comment]
Nope. They have been old friends and Stalrag should be present here. Maybe we can just cut Stalrag from existence entirely? He is not in the new NR either but as a cameo so I can just cut him off. So, TEG need not be edited. (you might have to edit the timeline though for TEG but that's another story)

**Comment by cooljeanius** [comment]
Remind me where Stalrag's scenario in NR is supposed to take place again? In relation to the location in Knalga where TEG starts, that is.

**Comment by cooljeanius** [comment]
> Remind me where Stalrag's scenario in NR is supposed to take place again? In relation to the location in Knalga where TEG starts, that is.

Never mind, I checked for myself
