### ISSUE TITLE
Have the Elvish Leader in The Great Gates and The Return keep at least some of his recall list.

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#14]
It seems odd that ALL the survivors died. Perhaps he could have some, as to make the fight slightly easier? All you have is inexperienced woses..

**Comment by cooljeanius** [comment]
I *think* it ought to be as simple as adding:
```
persistent=yes
save_id=Eowariand
```
...to the side declarations in question; I'll have to test that when porting to 1.16...

**Comment by cooljeanius** [comment]
halfway there as of aaff3f7 (or a third of the way there if you include the relevant part of #20 here as well)

**Comment by cooljeanius** [comment]
> I _think_ it ought to be as simple as adding:
> 
> ```
> persistent=yes
> save_id=Eowariand
> ```
> 
> ...to the side declarations in question; I'll have to test that when porting to 1.16...

ok so apparently this caused me to wind up with two Eowariands:
<img width="393" alt="Screen Shot 2022-06-08 at 20 29 43" src="https://user-images.githubusercontent.com/1388660/172739583-03880fa3-64e0-4c26-ae34-5d541470438c.png">
I'll try killing the one in the recall list...

**Comment by cooljeanius** [comment]
> I'll try killing the one in the recall list...

ok so yeah that worked; committed in e49491f
