### ISSUE TITLE
Make fighting Uga-Uga a more viable option in S4, Up The Mountain

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#15]
On Easy, S4 feels _too_ easy. I blast through the Ruffians and Woodsmen in no time, it feels like there's no challenge. Perhaps the AI could have 1-2 limited L2 recruits and several L1 recruits? Perhaps an event with reinforcements?

**Comment by cooljeanius** [comment]
sorry but complaints about Easy being "too easy" aren't ones I'm going to address; if some of the harder difficulties are too easy, then I can make those harder, but the easiest difficulty should actually be really easy.

**Comment by cooljeanius** [comment]
Also, another thing to note about this specific scenario: There's the choice as to whether to fight Uga-Uga, or pay him off. Which choice did you take? I guess I could reopen this if you think the two choices are unbalanced, such that one is always more clearly the better choice than the other...

**Comment by Ashmyr** [comment]
I always choose to pay him. Makes for more fun that way.

**Comment by cooljeanius** [comment]
> I always choose to pay him. Makes for more fun that way.

Hm, maybe I should offer a better reward for choosing to fight him, then...

**Comment by cooljeanius** [comment]
@Ashmyr I'm considering having the gold that Uga-Uga drops vary with difficulty; do you think it should increase with difficulty or decrease with difficulty? Currently the amount is 100 pieces...
(reopening since I am actually considering this now)

**Comment by cooljeanius** [comment]
> @Ashmyr I'm considering having the gold that Uga-Uga drops vary with difficulty; do you think it should increase with difficulty or decrease with difficulty? Currently the amount is 100 pieces... (reopening since I am actually considering this now)

@Ashmyr

**Comment by cooljeanius** [comment]
> @Ashmyr I'm considering having the gold that Uga-Uga drops vary with difficulty; do you think it should increase with difficulty or decrease with difficulty? Currently the amount is 100 pieces... (reopening since I am actually considering this now)

@Konrad22 WDYT?

**Comment by Konrad22** [comment]
I think it should decrease _slightly_ with difficulty. Maybe 100 90 80?
I'd like to note though that I don't remember there being mention that he'd drop gold if I beat him. At least not at the time where you have to choose whether you fight him.

**Comment by cooljeanius** [comment]
> I think it should decrease _slightly_ with difficulty. Maybe 100 90 80? I'd like to note though that I don't remember there being mention that he'd drop gold if I beat him. At least not at the time where you have to choose whether you fight him.

Hm, I guess I should word the hint a bit more explicitly then; I meant for Dulatus's "This could be an opportunity before us!" line to be kind of a hint, but I guess it wasn't obvious enough...

**Comment by cooljeanius** [comment]
Is the new wording in ecaa5b2 an improvement?

**Comment by Konrad22** [comment]
Yes, to me it clearly references a monetary reward.

**Comment by cooljeanius** [comment]
ok cool, guess I can re-close this now, then
