### ISSUE TITLE
Lessen The Difficulty on S12, Under Pressure

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#17]
The scenario is really difficult, even on Easy. It feels like a huge difficulty ramp, like if The South Guard suddenly became Northern Rebirth halfway through. I do know the scenario is _supposed_ to be a drain, but it feels like too much right now. Here's a few suggestions:

**Dark Forecast Style**
- Turns 1-5, the spawnpoints spawn Walking Corpses, Skeletons, Ghouls, Ghosts and Dark Adepts. Gives the player a little time to form defensive formations. Perhaps in the meantime you could have an enemy leader who recruits, maybe 2 or 3 to heighten up the pressure.
- Turns 5-10, the spawnpoints spawn Soullesses, Skeletons, Ghouls, Ghosts, Dark Adepts, Revenants, Deathblades, Bone Shooters. Gomating arrives on Turn 8, and on Turn 9, Hamel or Aiglathing says something like "These undead waves are getting worse." and then either "If only we had Clarissa", or "Perhaps the mage could do something about it if she got close enough." Perhaps you could have an enemy leader a considerable distance away who recruits a _lot_ of Level 2s and they start arriving now.
- Turns 10-20, the spawnpoints ramp up. They spawn Deathblades, Revenants, Bone Shooters, Necrophages, Shadows, Wraiths, Dark Sorcerers, Chocobones, and Soullesses. Gomating arrives back on turn 18 or so.
- Turns 20+, the difficulty seriously ramps up. An Ancient Lich appears and recruits level 3s with a lot of gold. This is to tell the player to get out FAST with Hamel, and where the real bloodbath begins.

**Other Suggestions**

- Perhaps make the castle easier to defend. If you saved loyal units maybe they could help you (ie, Clarissa might build some anti-undead hexes around the castle that undead can't step in, but the squares inside the hexes aren't enough to contain many units). More castles, a small moat, not anything over the top, and something a little restrained, but something to help with the bloodbath the player WILL get into.

- Perhaps make a way to deactivate the stones for a turn or 2. Maybe if a Lord or Dragonguard got to a stone he could temporarily fight it, deactivating it for 1 turn but he loses 10 health? Could be a way to provide a challenge for the player if they only have 1 mage, or if they have none at all.

**Comment by cooljeanius** [comment]
yeah I tried making this easier previously:

- 1319b9258f0eba27cc6fc729e0ad73393b336c29: Gave player extra gold and income
- 91169f2f9e8404681bbdbd301ba04fe0b62abbab: Weakened enemy spawns
- f2b2681b126a76cf2ea083d942669547d41706b2: Even more additional gold/income for the player, give them a keepful of units on EASY, reduce level required for Clarissa/Celylia to do their thing
- 67372fed2a9066391c6b2356ab5f93bb78b69cce: Additional free units on NORMAL too
- 509f0d8e2656ffe75924bb1e5d0ebed9f06fddfa: Made it easier for Gomating to escape
- ab4e697ab4fc40fc787af6fb917443f3e0eff5e6: Slowed enemy starting units and spawns, increased income, made it easier for Clarissa/Celylia to do their thing

...so, while I'm open to further making this scenario even easier, I think those previous changes should give you an idea of the types of easening I'd prefer to do: in other words, I just want to keep doing minor tweaks, rather than any sort of radical overhaul of the entire scenario.

**Comment by Ashmyr** [comment]
Got it. Sounds good. It's quite the unexpected difficulty jump and I think your changes will help.

**Comment by cooljeanius** [comment]
To be clear those are all changes that are already in the version you played; I'm just saying that future changes will most likely be along the same lines

**Comment by Ashmyr** [comment]
I understand, that's alright with me.

**Comment by cooljeanius** [comment]
> > The scenario is really difficult, even on Easy. It feels like a huge difficulty ramp,
> 
> The original author added a message about it being a recall list reducer. So the spike was intentional. Making it easier might upset their wishes though.

I think I'm just going to do a little bit of tinkering (like making some of the hints more explicit); it won't get *TOO* much easier

**Comment by cooljeanius** [comment]
@Ashmyr can you send me your savefile from the start of the scenario? I've always had Clarissa with me for this scenario, and it sounds like you didn't, so I'd like to be able to test the case where she's absent...

**Comment by cooljeanius** [comment]
Something that would be helpful here: a visual way to tell which monoliths have been deactivated vs. which ones are still spawning stuff... that would require either finding or creating some new art, though...

**Comment by cooljeanius** [comment]
> Something that would be helpful here: a visual way to tell which monoliths have been deactivated vs. which ones are still spawning stuff... that would require either finding or creating some new art, though...

Actually I guess it could just be done with halos...

**Comment by cooljeanius** [comment]
> > Something that would be helpful here: a visual way to tell which monoliths have been deactivated vs. which ones are still spawning stuff... that would require either finding or creating some new art, though...
> 
> Actually I guess it could just be done with halos...

ok that's done in [05c7419](https://github.com/cooljeanius/The_Earths_Gut/commit/05c741953b97c14fa303c896954667219c1a0551), so I think I'm done with this issue now.
