### ISSUE TITLE
S15: Explain composition of Kalenz's side better

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#18]
Konrad's recruit list feels too small. Perhaps an in-plot explanation of "the rest of the army split off from him due to a close encounter"? But that wouldn't make much sense..

You could give Kalenz's side more gold, but you also don't want to turn the scenario into an NR big battle.

**Comment by cooljeanius** [comment]
Konrad... doesn't actually have any recruits of his own? WDYM?

**Comment by Ashmyr** [comment]
I meant Kalenz's recruits. He says it's Konrad's recall list or whatever in the dialogue.

**Comment by cooljeanius** [comment]
Hm maybe I should just change that dialogue then
