### ISSUE TITLE
Balance The Enemy Sides in 5b (and other suggestions)

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#21]
The Undead are always crushed. The Trolls **always** get to the Lich before I do. It feels really unbalanced, and in my opinion, it should be more like the Subterranean Struggle scenario of UtBS, without the side-allying. Here's a few suggestions of my own (let's hope I get this formatting right..)
- [ ] The two chokeholds near the rail might be too easy of exploration points. I'd suggest adding a few loyal guard units for the enemy sides just outside of those hexes, far enough away that players can't see. The guard units could be L2 or several L1s, to encourage players to move along the rail westward.
- [ ] In the storage depot area, add a few extra Wraiths, Ghosts, Dark Adepts or Sorcerers. Perhaps add some units behind the trolls to encircle them. 
- [ ] Perhaps add a few ways for the sides to attack each other? This may not be the best suggestion as players could use it and they could easily stand back, but as soon as you get to the storage depot it feels like the sides just ignore each other and attack you.
- [ ] I'm not sure if this is me being lucky/unlucky but I always get the long route through the undead area. Is this intentional? It feels like it should be 50/50, but the way through the troll area is clearly shorter.

**Comment by cooljeanius** [comment]
Checking the code now; as for point 4, yes, it ought to be 50/50; here is where it is chosen: https://github.com/cooljeanius/The_Earths_Gut/blob/ba24879c3edcd65d4982d567a7f6f4a5692f7193/scenarios/05b_Unknown_tunnels.cfg#L580-L615

**Comment by cooljeanius** [comment]
@Ashmyr re: point 1: could you be a bit more specific about which chokeholds you mean? Like, give me some coordinates... 
...actually, on second thought, never mind. Exploration is good. I'm not going to be discouraging it.

re: point 2: by "storage depot" do you mean the large hall in the center? There are currently an equal number of "hall fighters" on each side that are placed there in the prestart event currently... 

re: point 3: I guess I can modify their AI values for that...

**Comment by cooljeanius** [comment]
So yeah I think aaff3f7 is all I'm going to do towards this
