### ISSUE TITLE
S10: Are the Undead and Troll sides supposed to be asynchronous?

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/The_Earths_Gut#3]
I started the scenario from the start-of-scenario save-file a few times to see if the generator was working.
I noticed that sometimes I got Trolls `side=6`  as my enemies and Undead `side=5` other times. If the scenario is supposed to be designed like that then it's okay, and I shall close the issue. Otherwise, it might be worth looking into.

The goblins and orcs were present in every instance so, I guess they are okay.

One peculiar case: One time the Death Knight leader spawned near the Orc base but it had no Keep to recruit from. This has occurred just once so I speculate this is a very rare chance.

**Comment by cooljeanius** [comment]
What difficulty are you playing on? On Easy, one of the two sides randomly gets killed; see lines 414 to 441: https://github.com/cooljeanius/The_Earths_Gut/blob/master/scenarios/10_Old_friends.cfg#L414

**Comment by knyghtmare** [comment]
Oh, I didn't check the difficulty of the save file. Setting it to hard presented both sides. I guess I can close this now.
