### ISSUE TITLE
S8 Lost, make note about what trolls you keep rereadable

### ISSUE THREAD

**Issue by Konrad22** [cooljeanius/The_Earths_Gut#42]
As it is, you are shown this information once, and never again until you have to pick what trolls you keep.
Make it available via right click menu.

**Comment by cooljeanius** [comment]
There's another scenario that I could probably copy from here; I think it might have been the Ferry Crossing one?

**Comment by Konrad22** [comment]
> There's another scenario that I could probably copy from here; I think it might have been the Ferry Crossing one?

Yes, there is a 'help' accessible via right click, explaining how boarding and all that works.

**Comment by cooljeanius** [comment]
ok after [6f3e760](https://github.com/cooljeanius/The_Earths_Gut/commit/6f3e760c5b4d0a55cd7868a0a70d5a0f85d03c87) a menu option now gets added; the call to `[fire_event]` to actually display the message automatically in the `prerecruit` event where it's added doesn't seem to work, though...

**Comment by cooljeanius** [comment]
ok cb5a47f now causes the message to be displayed automatically in the `prerecruit` event again; I think we ought to be good here now...
