### ISSUE TITLE
S8 - Lost, give the player villages they might have not taken once you can recruit

### ISSUE THREAD

**Issue by Konrad22** [cooljeanius/The_Earths_Gut#44]
Before you free Krolock, there is no incentive for you to take villages beyond heling units. So, you might not have taken all 4 villages you had in your reach up to this point. Later, when you can recruit, the villages are far, far away, so you can't just take them now.
-> Give those villages to the player once they can recruit.
![grafik](https://user-images.githubusercontent.com/39015360/218340658-cbf9e7d2-ff74-4f1c-9214-67222b8ddcf5.png)

**Comment by cooljeanius** [comment]
I already did this one, too; I combined this one with the commit in which I updated the Death Baron animations: 5bc1807
