### ISSUE TITLE
Translatability

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#6]
Currently, `wmlxgettext` chokes on `utils/abilities.cfg` when trying to generate a `.pot` file; that will have to be fixed if this campaign is ever going to be translatable.

**Comment by cooljeanius** [comment]
(I've tried adjusting the magic comments, but that only seems to make things worse if I go much further with them...)

**Comment by CelticMinstrel** [comment]
I'm not quite sure, but is it possible that you need a `# wmlxgettext: [attack]` above this line?

https://github.com/cooljeanius/The_Earths_Gut/blob/master/utils/abilities.cfg#L83

**Comment by cooljeanius** [comment]
> I'm not quite sure, but is it possible that you need a `# wmlxgettext: [attack]` above this line?
> 
> https://github.com/cooljeanius/The_Earths_Gut/blob/master/utils/abilities.cfg#L83

That just changes the error from this:
```
$ ./wmlxgettext --domain=wesnoth-The_Earths_Gut --directory=/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application\ Support/Wesnoth_1.14/data/add-ons/The_Earths_Gut --recursive -o /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application\ Support/Wesnoth_1.14/data/add-ons/The_Earths_Gut/translations/TEG.pot
error: The_Earths_Gut/utils/abilities.cfg:93: unexpected closing tag '[/attack]' outside any scope.
```
...into this:
```
$ ./wmlxgettext --domain=wesnoth-The_Earths_Gut --directory=/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application\ Support/Wesnoth_1.14/data/add-ons/The_Earths_Gut --recursive -o /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application\ Support/Wesnoth_1.14/data/add-ons/The_Earths_Gut/translations/TEG.pot
error: The_Earths_Gut/utils/abilities.cfg:210: End of WML file reached, but some tags were not properly closed.
(nearest unclosed tag is: [specials])
```

**Comment by CelticMinstrel** [comment]
Then add this at the end of the file:

```
# wmlxgettext: [/specials]
# wmlxgettext: [/attack]
```

**Comment by cooljeanius** [comment]
> Then add this at the end of the file:
> 
> ```
> # wmlxgettext: [/specials]
> # wmlxgettext: [/attack]
> ```

ok that works; thanks!

**Comment by cooljeanius** [comment]
potfile successfully generated; closing!
