### ISSUE TITLE
S09: Nightmare shouldn't say "Death to the living!" when he can recruit living Dark Adepts himself

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#9]
It doesn't make sense for the Nightmare to say "Death to the living!" and then only attack some of the living. Either change the dialogue (easier, but still kind of nonsensical), or change the undead side to be its own team (would require some rebalancing, which would be harder, but make more sense).

**Comment by cooljeanius** [comment]
(originally reported by @knyghtmare on Discord)

**Comment by cooljeanius** [comment]
ok so PR #10 from @Ashmyr should address this; I'll still need to test it myself, though... hey @knyghtmare WDYT?

**Comment by cooljeanius** [comment]
Actually, wait. The name of the scenario is "Unusual Allies". Does that refer to the player and the trolls, or all the enemy sides that had previously allied to oppose the player, before we put them on separate teams?

**Comment by knyghtmare** [comment]
Seems okay to me. Would probably require a quick playtest to see what happens.

**Comment by cooljeanius** [comment]
> Seems okay to me. Would probably require a quick playtest to see what happens.

I'm testing it now; I'll probably be adding some additional changes...

**Comment by cooljeanius** [comment]
ok, so after testing @Ashmyr's changes, the enemy sides don't actually fight each other that much, meaning that the extra gold they get pretty much just straight-up buffs them, rather than compensating for any infighting they're supposed to do... I think I might want to give the player and the allied trolls some more gold, too?

**Comment by Ashmyr** [comment]
Hmmm...alright. Makes sense to buff the player too. Maybe if there's `target` WML you could remove it so they focus on each other? When I played it they did target the allied Troll side more...though the Goblins raided the SE trolls a lot.

**Comment by cooljeanius** [comment]
Oh, and there still remains the issue of the undead being able to recruit Dark Adepts, too...

**Comment by cooljeanius** [comment]
> Oh, and there still remains the issue of the undead being able to recruit Dark Adepts, too...

Retitling this issue to just be about this part

**Comment by knyghtmare** [comment]
> Oh, and there still remains the issue of the undead being able to recruit Dark Adepts, too...

just replace those Adepts with a custom skeletal mage unit. Ageless Era has loads of them.

**Comment by cooljeanius** [comment]
So, when I played through this scenario for the first time, it was my first chance to experience the "Berserker laughs when attacking a Dark Adept" Easter Egg, and that was memorable for me and something I'd like to preserve, so if I change it to a different unit, I'd want to make sure it's also one that doesn't have any melee attacks. Although, actually, I just got a different idea for how I could fix this, so I don't think I'll be using a different unit after all...

**Comment by cooljeanius** [comment]
ok fixed by bb57467
